import type { Provider } from "./utils";

export const allProviders: Provider[] = [
  {
    id: 1,
    email: "adam.jones@gmail.com",
    phone: "+44 20 7946 0958",
    postcode: "SW1A 1AA",
    vendorType: "Independent",
    serviceOffering: "Housekeeping",
    signupDate: "2024-05-01",
    status: "Onboarded",
  },
  {
    id: 2,
    email: "maria.smith@cleaners.uk",
    phone: "+44 161 555 2211",
    postcode: "M1 1AE",
    vendorType: "Company",
    serviceOffering: "Window Cleaning",
    signupDate: "2024-06-14",
    status: "Rejected",
  },
  {
    id: 3,
    email: "lucas.brown@app.com",
    phone: "+44 121 333 7788",
    postcode: "OX1 2JD",
    vendorType: "Independent",
    serviceOffering: "Car Valet",
    signupDate: "2023-11-03",
    status: "Onboarded",
  },
  {
    id: 4,
    email: "emma.johnson@service.uk",
    phone: "+44 113 777 9900",
    postcode: "E1 6AN",
    vendorType: "Company",
    serviceOffering: "Housekeeping",
    signupDate: "2025-01-25",
    status: "Onboarded",
  },
  {
    id: 5,
    email: "george.miller@housekeep.uk",
    phone: "+44 20 7946 0958",
    postcode: "B1 1AA",
    vendorType: "Independent",
    serviceOffering: "Window Cleaning",
    signupDate: "2023-09-10",
    status: "Rejected",
  },
  {
    id: 6,
    email: "olivia.clark@app.com",
    phone: "+44 20 7946 0958",
    postcode: "W1A 1HQ",
    vendorType: "Company",
    serviceOffering: "Car Valet",
    signupDate: "2024-12-20",
    status: "Onboarded",
  },
  {
    id: 7,
    email: "david.wilson@cleaners.uk",
    phone: "+44 161 555 2211",
    postcode: "SW1A 1AA",
    vendorType: "Independent",
    serviceOffering: "Window Cleaning",
    signupDate: "2025-03-09",
    status: "Rejected",
  },
  {
    id: 8,
    email: "sarah.white@house.uk",
    phone: "+44 113 777 9900",
    postcode: "M1 1AE",
    vendorType: "Company",
    serviceOffering: "Housekeeping",
    signupDate: "2024-04-17",
    status: "Onboarded",
  },
  {
    id: 9,
    email: "daniel.james@app.com",
    phone: "+44 20 7946 0958",
    postcode: "OX1 2JD",
    vendorType: "Independent",
    serviceOffering: "Car Valet",
    signupDate: "2025-02-05",
    status: "Onboarded",
  },
  {
    id: 10,
    email: "sofia.green@window.uk",
    phone: "+44 121 333 7788",
    postcode: "E1 6AN",
    vendorType: "Company",
    serviceOffering: "Window Cleaning",
    signupDate: "2024-03-01",
    status: "Rejected",
  },
  ...Array.from(
    { length: 40 },
    (_, i): Provider => ({
      id: i + 11,
      email: `user${i + 11}@example.com`,
      phone: "+44 20 7946 0958",
      postcode: [
        "SW1A 1AA",
        "M1 1AE",
        "OX1 2JD",
        "E1 6AN",
        "B1 1AA",
        "W1A 1HQ",
      ][i % 6],
      vendorType: (i % 2 === 0
        ? "Independent"
        : "Company") as Provider["vendorType"],
      serviceOffering: ["Housekeeping", "Window Cleaning", "Car Valet"][
        i % 3
      ] as Provider["serviceOffering"],
      signupDate: ["2024-05-01", "2025-03-21", "2023-10-11"][i % 3],
      status: ["Onboarded", "Rejected"][i % 2] as Provider["status"],
    })
  ),
];
